- name: get Pix script version
  command: pix version
  register: pix_version_result
  changed_when: false

- name: check Pix script version
  assert:
    that: "'{{ pix_cli_version }}' in pix_version_result.stdout"
